# ==============================================================================
#                                INTEGRATIONS
# ==============================================================================
# KernelSU & SUSFS versions
# https://github.com/tiann/KernelSU/commits/main/
# https://gitlab.com/simonpunk/susfs4ksu/-/tree/gki-android14-6.1
# https://gitlab.com/simonpunk/susfs4ksu/-/tree/gki-android16-6.12
# To update these components, specify the latest commit hashes from the repositories above
KSU_COMMIT="85cab5f841b55bed180c10dfdbe33f876aba7820"
SUSFS_KSU_COMMIT_6_1="273ae364c5b7c92ceb15634c9f075b6fc0501048"
SUSFS_KSU_COMMIT_6_12="c8f64e41e3dea2cd44754d7472d3cd0bc0b40784"
SUSFS_KSU_COMMIT_6_6="9d9464f191b2d846590ac4d1b52e123df135c401"

# ==============================================================================
#                                AVB METADATA
# ==============================================================================
# Filled based on the AVB metadata of the original boot.img.
# Changing these fields is not strictly necessary, but can be done if required.
# To extract the data, use avbtool.py:
#   python3 ./avbtool.py info_image --image [original_boot.img]
#   Link to avbtool.py: https://android.googlesource.com/platform/external/avb/+/refs/heads/main-kernel/avbtool.py

STABLE_rollback_index=1788566400
STABLE_salt=74231b8e5c5951f47024d8ebaa3e662812e765bef6336c1edc8752d53cf38326
STABLE_os_version=17
STABLE_fingerprint=google/shiba/shiba:17/CP3A.260905.009/16091614:user/release-keys
STABLE_security_patch=2026-09-05

BETA_rollback_index=1785888000
BETA_salt=1f638cdba97867ab0034b24824e4c367a475f1c088fd5676cf7e065e446f9b80
BETA_os_version=17
BETA_fingerprint=google/shiba_beta/shiba:17/CP41.260828.004.A8/16319058:user/release-keys
BETA_security_patch=2026-08-05

# ==============================================================================
#                                FIRMWARE BRANCHES
# ==============================================================================
# Determines the GKI kernel source branch cloned from: https://android.googlesource.com/kernel/common/+refs
# To choose the correct branch, check the "Makefile" in the root of the kernel repository.
# The version numbers are specified in the Makefile header (e.g., VERSION = 6, PATCHLEVEL = 1, SUBLEVEL = 157).
# This version must match the kernel version of your installed firmware.

STABLE_BRANCH="android15-6.6-2026-07"
BETA_BRANCH="android15-6.6-2026-04"

# ==============================================================================
#                        BUILD TOOLS & PIXEL DRIVERS
# ==============================================================================
# Contains drivers, build tools, etc.
# Cloned to kernel_pixel_6.1 / kernel_pixel_6.12 / kernel_pixel_6.6 from:
#   Kernel 6.1:  https://gitlab.com/grapheneos/kernel_pixel_6.1 (PIXEL_TAG)
#   Kernel 6.12: https://gitlab.com/grapheneos/kernel_pixel_6.12 (PIXEL_SPACECRAFT_BRANCH)
#   Kernel 6.6:  https://gitlab.com/grapheneos/kernel_pixel_6.6 (PIXEL_TAG / PIXEL_SPACECRAFT_BRANCH)
# DO NOT CHANGE unless you know what you are doing
PIXEL_TAG="2026091700"
PIXEL_SPACECRAFT_BRANCH="17-base"
DEVICE="muzel"

# ==============================================================================
#             EXPERIMENTAL INTEGRATIONS (REQUIRES MANUAL FIXES)
# ==============================================================================
# KernelSU-Next & SukiSU integration

KSU_NEXT_COMMIT="HEAD"
