# ==============================================================================
#                                INTEGRATIONS
# ==============================================================================
# KernelSU & SUSFS versions
# https://github.com/tiann/KernelSU/commits/main/
# https://gitlab.com/simonpunk/susfs4ksu/-/tree/gki-android14-6.1
# https://gitlab.com/simonpunk/susfs4ksu/-/tree/gki-android16-6.12
# To update these components, specify the latest commit hashes from the repositories above
KSU_COMMIT="85cab5f841b55bed180c10dfdbe33f876aba7820"
SUSFS_KSU_COMMIT_6_1="9d9464f191b2d846590ac4d1b52e123df135c401"
SUSFS_KSU_COMMIT_6_12="9d9464f191b2d846590ac4d1b52e123df135c401"
SUSFS_KSU_COMMIT_6_6="9d9464f191b2d846590ac4d1b52e123df135c401"

# ==============================================================================
#                                AVB METADATA
# ==============================================================================
# Filled based on the AVB metadata of the original boot.img.
# Changing these fields is not strictly necessary, but can be done if required.
# To extract the data, use avbtool.py:
#   python3 ./avbtool.py info_image --image [original_boot.img]
#   Link to avbtool.py: https://android.googlesource.com/platform/external/avb/+/refs/heads/main-kernel/avbtool.py

STABLE_rollback_index=1780272000
STABLE_salt=2dcdc70b5d30387545bb940a97b68815a2312880ee79855ac80fa5617181965c
STABLE_os_version=16
STABLE_fingerprint=google/lineage_frankel/frankel:16/BP4A.251205.006/eng.androi:userdebug/release-keys
STABLE_security_patch=2026-05-05

BETA_rollback_index=1780272000
BETA_salt=2dcdc70b5d30387545bb940a97b68815a2312880ee79855ac80fa5617181965c
BETA_os_version=16
BETA_fingerprint=google/lineage_frankel/frankel:16/BP4A.251205.006/eng.androi:userdebug/release-keys
BETA_security_patch=2026-05-05

# ==============================================================================
#                                FIRMWARE BRANCHES
# ==============================================================================
# Determines the GKI kernel source branch cloned from: https://android.googlesource.com/kernel/common/+refs
# To choose the correct branch, check the "Makefile" in the root of the kernel repository.
# The version numbers are specified in the Makefile header (e.g., VERSION = 6, PATCHLEVEL = 1, SUBLEVEL = 157).
# This version must match the kernel version of your installed firmware.

STABLE_BRANCH="android15-6.6-2025-10"
BETA_BRANCH="android15-6.6-2025-10"

# ==============================================================================
#                        BUILD TOOLS & PIXEL DRIVERS
# ==============================================================================
# Contains drivers, build tools, etc.
# Cloned to kernel_pixel_6.1 / kernel_pixel_6.12 / kernel_pixel_6.6 from:
#   Kernel 6.1:  https://gitlab.com/grapheneos/kernel_pixel_6.1 (PIXEL_TAG)
#   Kernel 6.12: https://gitlab.com/grapheneos/kernel_pixel_6.12 (PIXEL_SPACECRAFT_BRANCH)
#   Kernel 6.6:  https://gitlab.com/grapheneos/kernel_pixel_6.6 (PIXEL_TAG / PIXEL_SPACECRAFT_BRANCH)
# DO NOT CHANGE unless you know what you are doing
PIXEL_TAG="2026052400"
PIXEL_SPACECRAFT_BRANCH="16-qpr2"
DEVICE="muzel"

# ==============================================================================
#             EXPERIMENTAL INTEGRATIONS (REQUIRES MANUAL FIXES)
# ==============================================================================
# KernelSU-Next & SukiSU integration

KSU_NEXT_COMMIT="HEAD"
